// Contains all the Action types used in App.
export const SHOW_RETRY_UI = 'SHOW_RETRY_UI';
export const DELETE_RETRY_UI = 'DELETE_RETRY_UI';
export const FETCH_ALL_POKEMONS_LOADING = "FETCH_ALL_POKEMONS_LOADING";
export const FETCH_ALL_POKEMONS_SUCCESS = "FETCH_ALL_POKEMONS_SUCCESS";
export const FETCH_ALL_POKEMONS_FAILURE = "FETCH_ALL_POKEMONS_FAILURE";
export const FETCH_ALL_POKEMONS_CLEAR = "FETCH_ALL_POKEMONS_CLEAR";
export const FETCH_POKEMON_DETAIL_LOADING = "FETCH_POKEMON_DETAIL_LOADING";
export const FETCH_POKEMON_DETAIL_SUCCESS = "FETCH_POKEMON_DETAIL_SUCCESS";
export const FETCH_POKEMON_DETAIL_FAILURE = "FETCH_POKEMON_DETAIL_FAILURE";
export const FETCH_POKEMON_DETAIL_CLEAR = "FETCH_POKEMON_DETAIL_CLEAR";
export const FETCH_POKEMON_CARD_LOADING = "FETCH_POKEMON_CARD_LOADING";
export const FETCH_POKEMON_CARD_SUCCESS = "FETCH_POKEMON_CARD_SUCCESS";
export const FETCH_POKEMON_CARD_FAILURE = "FETCH_POKEMON_CARD_FAILURE";
export const FETCH_POKEMON_CARD_CLEAR = "FETCH_POKEMON_CARD_CLEAR";